spring.application.name=springboot

#Cấu hình kết nối đến DB, nếu chưa có DB sẽ tự động tạo
spring.datasource.url=jdbc:mysql://localhost:3306/cua_hang_sach?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Cấu hình DDL tự động tạo hoặc cập nhật bảng
spring.jpa.hibernate.ddl-auto=update
